// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Gang struct {
	ID                int32
	Name              string
	EntryPasswordHash string
	CreatedAt         pgtype.Timestamptz
}

type User struct {
	ID         int32
	Name       string
	AvatarPath pgtype.Text
	CreatedAt  pgtype.Timestamptz
	LastLogin  pgtype.Timestamptz
}

type UsersGang struct {
	UserID int32
	GangID int32
	Ishost pgtype.Bool
}
