// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Gang struct {
	ID                int32
	Name              string
	EntryPasswordHash string
	CurrentlyInGame   bool
	CreatedAt         pgtype.Timestamptz
}

type User struct {
	ID         int32
	Name       string
	AvatarPath pgtype.Text
	CreatedAt  pgtype.Timestamptz
	LastLogin  pgtype.Timestamptz
}

type UsersGang struct {
	UserID       int32
	GangID       int32
	Ishost       bool
	AssociatedAt pgtype.Timestamptz
}

type Video struct {
	VideoID      string
	Title        string
	Description  pgtype.Text
	ThumbnailUrl pgtype.Text
	ChannelName  string
}

type VideoSubmission struct {
	ID        int32
	UserID    int32
	GangID    int32
	VideoID   string
	CreatedAt pgtype.Timestamptz
}
